### ISSUE TITLE
redraw datatable when action is performed

### ISSUE THREAD

**Issue by hamza-dev1** [bhaveshpatel200/vue3-datatable#18]
Hi, how i can reload data in datatable after deleting a row or making any change in the server?

Thanks

**Comment by hamza-dev1** [comment]
I solved the issue. After performing update operation for 1 single column i'm calling the same endpoint from that returns all the data, i know that it isn't the best solution and will impact performance. I would love to hear any other suggestions!
Thanks

**Comment by bhaveshpatel200** [comment]
HI,

If you are using server side rendering then its good to call same endpoint to redraw updated data after updating single row data.

and if you are using client side rendering then you can update that row from all data variables which you have passed as params instead of calling same endpoints.

because here if server side getting only page wise data which is not taking time, and client side getting all data in single api call which getting slow down to call api every time.
