### ISSUE TITLE
ssue with vue3-otp-input-field and Other Packages Causing Errors in Vristo Theme

### ISSUE THREAD

**Issue by mohammadali10-12** [bhaveshpatel200/vue3-datatable#58]
I have purchased and set up the Vristo Tailwind Vue.js theme for my project. The theme works fine with the default setup, but issues arise when I try to install additional third-party packages such as vue3-otp-input-field. After installing this package (or similar packages), the application throws an error and fails to start.

I believe the issue may stem from compatibility problems between the Vristo theme's setup and these external packages, potentially related to how the theme handles its dependencies or the bundling process.

Despite following the official Vue.js installation and setup guidelines, the problem persists, making it impossible to extend the theme’s functionality with any new packages. Since Vristo is a paid theme and not open-source, I am unable to investigate the root cause in-depth.

This is critical as it prevents me from using common Vue.js packages that are essential for my project’s functionality

**Comment by bhaveshpatel200** [comment]
Yes, correct PatrickCaneloDigital.

This is not any theme regarding issues because any third party packages has their own dependency which will not met with our version that's why that package is not works.

By the way Vristo is updated with all latest packages, so you guys can download latest copy from themeforest.
